### ISSUE TITLE
Mail (still?) getting dropped due to 421 SPF and 550 DKIM errors -- maybe left over from March fix?

### ISSUE THREAD

**Issue by jayporter** [niftylettuce/forward-email#122]
Hi there,

This may be a continuation of the issue from around March 10th that you fixed.  (Thank you for offering this service!)

After the fix was posted, *almost* all my mail started coming through.  However it's since become clear that email from a couple domains is not.  

One sender asked his provider to look into why I wasn't getting mail, and the response was:  

"Their mail server is having DNS problems that are causing them to lose incoming messages - something the administrator should be aware of - if not, they may need to change providers (we're able to offer our services, of course).  It's not anything anyone else can diagnose except to say these are the two errors they have been sending back to us:

421 SPF validation failed with result "temperror" and explanation "SPF Temporary Error: DNS: TCP Fallback error: no working nameservers found"
421 SPF validation failed with result "permerror" and explanation "SPF Permanent Error: Too many DNS lookups"

Meanwhile, my dad has trying to send me email from his gmail account, which bounces back to  him with the following error:

"550 The email you sent has an invalid DKIM signature, please try again or check your email service's DKIM configuration. If you believe this is an error, please forward this email to: support@forwardemail.net".

Is there something I need to change on my DNS configuration to accommodate?  Thank you for any help or suggestions you can give.

Best
Jay

**Comment by niftylettuce** [comment]
These seem like errors from the sender's end, not yours (or mine on forwardemail.net).  Both SPF errors they receive indicate that their SPF setup does not comply with RFC standards.  The error "Too many DNS lookups" comes from the SPF lookup exceeding 10 DNS hops https://jangomail.com/spf-too-many-lookups-error/.  The other error "no working nameservers found" means that their nameservers are messed up.

If you can email me at niftylettuce@gmail.com with the sender's FROM address for each of these errors I can further investigate for you privately.

I'm guessing your dad is sending from a Gmail Business account?  If so have him ensure that his DKIM setup is working properly, because the only time he'd get that error is if it was incorrectly setup - so technically having this error is a good thing in that it helps us fix something setup incorrectly perhaps by mistake.

Hope this helps, feel free to reach out to my email.

**Comment by jayporter** [comment]
Thank you very much for all your help, just wanted to note here in the issues forum that your initial response was correct; we (you) were able to pinpoint the problems with the configuration of both senders.  

Thanks again -
Jay
