### ISSUE TITLE
The response from the remote server was:  421 Timeout - closing connection 

### ISSUE THREAD

**Issue by dagelf** [niftylettuce/forward-email#129]
I've been getting these when sending to forwardemail addresses. It's not exactly clear whether it's a timeout on the forwardemail.net server itself, or if the server emits it when it experiences a timeout - what is the capacity of the current hosting? I think you should start charging a small fee - as either way, people are going to have to pay to host it - and a bigger server should work out cheaper than everyone paying for individual small servers... assuming it is a server capacity problem, BTW congrats on picking up so much traffic! :100:

**Comment by niftylettuce** [comment]
I'll take a look at this asap, thanks @dagelf

**Comment by niftylettuce** [comment]
V2 is released, and I am setting up load balancing and a status page later

**Comment by niftylettuce** [comment]
To anyone that still encountered this issue, there was one more bug due to host normalization that needed fixed.  It's all resolved now though, was pesky to track down! 🎉 

Any further issues, questions, or feature requests, please let us know.

v6.1.4 has been released and deployed, which fixed this issue through some added "host normalization" logic.
