### ISSUE TITLE
No more "via gmail.com"?

### ISSUE THREAD

**Issue by maganvill** [niftylettuce/forward-email#144]
This is an excellent project, thank you so much :)

Is there by any change possible to implement a solution to getting rid of "via gmail.com" that appears on mail received on gmail, sent from gmail with custom domain through forwardemail.net? I guess the same applies when sent mails ends up in spam filter. 

I'm not into the details. But it seams the domain is not authenticated?

**Comment by youdly** [comment]
I assumed you unchecked the "Treas as an alias"?
I think this is more of limitation (security feature?) of gmail. I noticed (https://github.com/niftylettuce/forward-email/pull/141) Gmail add/change the `Return-Path` value in the header to my gmail address, which is different from `From` value (custom domain). I believe this is the cause of "via gmail.com".

Maybe enterprise user is allowed to change the `Return-Path` value.

**Comment by VAD37** [comment]
I check "Treat as an alias" option. I still have "via gmail"
I try setup Postmark in DNS but I also receive weekly report from Postmark say that all email sent are 'SPF and DKIM not aligned'

I think this happen because we did not have DKIM key verification for website domain.

**Comment by maganvill** [comment]
Do you need both p=none and to somehow force gmail to set `Return-Path` to same as `From`, or is one enough? 

Maybe gmail has locked down external domain registrars and requires you to use Google Domain Services (which I can't since they don't support my TLD yet) for full DMARC message security?

**Comment by youdly** [comment]
@VAD37 
"Treat as an alias" definitely results in "via gmail" because Gmail would treat the custom domain as [_alias_](https://support.google.com/a/answer/1710338) of your gmail address. Postmark's explanation on the 'SPF and DKIM not aligned':
> google.com is authorized to send on behalf of custom-domain.com, however it looks like SPF and DKIM are still failing DMARC’s alignment test. DMARC looks at the Return-Path of a message to make sure the domain there matches the domain in your From address. If the Return-Path path doesn’t match your From address, those messages will fail DMARC’s SPF alignment test. Set up a DKIM record and check with this source about setting up custom Return-Path.
As I mentioned in previous comment, while the `From` value is your custom domain, gmail use your gmail address as the `Return-Path` value; different domain=DMARC fail.

@maganvill 
you mean `p` and `sp` values? I set both to none. I don't think we can change gmail's `Return-Path` behavior through dmarc policy. Gmail probably does it to prevent abuse.
I don't think Google Domain would help, best chance I think is Gsuite.

That's my current understanding anyway, any expert please correct me.

**Comment by niftylettuce** [comment]
This is a Gmail limitation
