### ISSUE TITLE
Ability to "send mail as" from Gmail

### ISSUE THREAD

**Issue by niftylettuce** [niftylettuce/forward-email#2]
We'd need to enable AUTH command and add `onAuth` option via <https://nodemailer.com/extras/smtp-server/#handling-authentication>.  Perhaps we only allow sending mail as from Gmail for now?

**Comment by kitling** [comment]
for password based auth, one way would be to store the hash of the password as a TXT field on DNS. however, I don't think this is a very good idea as it could lead to offline hash attacks.

therefore, I suggest some PKI scheme (PGP?), encrypting the hash before sending it to putting it on DNS. That way, the only one that can decrypt the hash is the one running the server, and then a normal password hashing scheme can be used on top of that.

**Comment by mendelk** [comment]
Curious what the status on this is? This is the only thing blocking me from using this because I'd also need to send email under the address!

Thanks for the awesome work!

**Comment by matheus-rosin** [comment]
Hi! Can you give some help about just that that @mendelk had said? After correctly forwarding emails for my gmail account, when trying to send emails setting smtp configs, I am getting "550 Message failed: 550-5.7.1 Unauthenticated email from google.com is not accepted due to domain's". And I don't know how to proceed hahah
Thanks in advance!

**Comment by FGRibreau** [comment]
@niftylettuce discovered your service today, moved 3 SaaS over it, awesome piece of work! Really.
Highly interested by this, how much would it costs for you to implement it?

**Comment by niftylettuce** [comment]
@FGRibreau I've already begun this feature along with #3 😄

**Comment by transf** [comment]
@niftylettuce, thanks, can't wait. This will be really useful for my business as I'm not really ready to get GSuite.

**Comment by FGRibreau** [comment]
@niftylettuce any way we can help? Could you share the branch with us?

**Comment by niftylettuce** [comment]
I plan to dedicate time this weekend, wrapping up work for my company right now 👏

**Comment by niftylettuce** [comment]
@FGRibreau feel free to join in slack guys so you are first to know when its up! [Join Slack Channel](http://slack.crocodilejs.com/)

**Comment by madakk** [comment]
@niftylettuce using 'send mail as' from Gmail should already be possible using Gmail's own SMTP without any modifications on forwardemail's end (for example see [this guide](https://www.thedigitalnonprofit.com/blog/use-gmail-own-domain-free)). However, this currently fails at the verification stage, as forwardemail rejects the verification email from being forwarded due to DMARC authentication. Is there no way to work around this? If it was just possible to get the verification code which currently gets blocked, this should be working fine.

**Comment by niftylettuce** [comment]
✅ support has been added and deployed, please try it out

documentation is available at https://github.com/niftylettuce/forward-email#send-mail-as-using-gmail

**Comment by matheus-rosin** [comment]
Great, thanks! :)

**Comment by FGRibreau** [comment]
It even works with Google Apps business account, will send a PR to the step-by-step guide :+1:

**Comment by partev** [comment]
Successfully went through all the steps including the verification step, while using and IDN domain. However, when sending email using this domain get the following error from Google.

> Final-Recipient: rfc822; destination_address@gmail.com
Action: failed
Status: 5.0.0
Diagnostic-Code: smtp; [209.85.220.41      11] Our system has detected that this message is not RFC 5322 compliant: 'From' header has non compliant domain name. To reduce the amount of spam sent to Gmail, this message has been blocked. Please visit https://support.google.com/mail/?p=RfcMessageNonCompliantand review RFC 5322 specifications for more information. p25-v6sor16468ejr.25 - gsmtp
Last-Attempt-Date: Tue, 02 Oct 2018 18:11:12 -0700 (PDT)

So it looks like Google's SMTP server does not support IDN domain names and there is nothing forward-email can do about it. Maybe add a sentence to the documentation mentioning that?
