### ISSUE TITLE
yahoo problem 550, help me

### ISSUE THREAD

**Issue by gossvald** [niftylettuce/forward-email#39]
Hi, today I started using the forwardemail.net service, when I was trying to send an email from a yahoo account, It return "550: Message failed: 550-5.7.1 Unauthenticated email from yahoo.com is not accepted due to domain's" .

Can you help me with this problem, has it happened to you?

Thank you very much.

Best regards.

**Comment by teodors** [comment]
I experienced the same problem and error message with Google. If you read docs carefully, you should find that "send mail as" or aliases is not yet supported, although it should be possibe sometime very soon, fingers crossed.

https://forwardemail.net/#/?id=can-i-send-mail-as-with-this

**Comment by niftylettuce** [comment]
@teodors any idea how to fix this for Yahoo?

**Comment by astrob0t** [comment]
@niftylettuce , Yahoo have updated their DMARC policy record with `p=reject` [(source)](https://help.yahoo.com/kb/SLN24016.html), which tells other DMARC compliant systems to reject mail that doesn't originate from a Yahoo server. This is the same issue as the Gmail's `550-5.7.1 Unauthenticated email from google.com is not accepted due to domain's DMARC policy` error. 

A way to mitigate this would be to use the sender's name in the friendly from. A “friendly from” is when you use a name to appear as the from address, instead of the email address itself:
`exampleuser@yahoo.com` can be sent as `“Example User” <forwarder@forwardemail.net>` and also add a `reply-to` header of `exampleuser@yahoo.com`. This way the recipients still recognize the individual that sent the message, and you’re no longer at risk of violating the DMARC policy.

**Comment by niftylettuce** [comment]
This issue should be fixed, please try again! @gossvald @teodors
