### ISSUE TITLE
how to reduce spam more

### ISSUE THREAD

**Issue by bauripalash** [niftylettuce/forward-email#69]
I am using this service for few months and today I received a disgusting spam email from `no-reply@forwardemail.net`

Here are some screenshots of that e-mail : 

![screenshot_2018-12-11-22-53-25](https://user-images.githubusercontent.com/16154204/49817997-abdbd500-fd97-11e8-85a1-81e486cd2795.png)

![screenshot_2018-12-11-22-53-36](https://user-images.githubusercontent.com/16154204/49818006-b4341000-fd97-11e8-8f66-23573dd7a1f4.png)

**Comment by wei** [comment]
Can you post the full email header?

![image](https://user-images.githubusercontent.com/5880908/49818605-2cbbb200-fd41-11e8-81ee-be22a030a499.png)

**Comment by astrob0t** [comment]
This looks like any generic spam email sent from a random domain, which you can just delete. The sender domain seems to have DMARC restricted policy. So forward-email service is rewriting the headers to have a "friendly from". The actual sender's mail id would be in the reply-to header. This implementation allows people to send email from legitimate providers like yahoo and AOL but can't protect from bad senders. That's where Gmail's anti-spam kicks in and saves our day. 
@niftylettuce we would need to improve the docs to educate the end users about this.

**Comment by bauripalash** [comment]
@wei Here's the file: https://drive.google.com/file/d/1RJAN5PWpK__KgF_1sitnq7Ce_c62rh_x/view?usp=drivesdk

**Comment by bauripalash** [comment]
![screenshot_2018-12-12-14-36-50](https://user-images.githubusercontent.com/16154204/49858638-7aa4e880-fe1b-11e8-876f-ef24555779c4.png)
Seems like it is coming from the domain `@barprowler.com`

**Comment by astrob0t** [comment]
Ok. This is definitely a spam which you can just delete.. There doesn't seem to be any problem with the service. The mail id **no-reply@forwardemail.net** is just a mail forwarder/relay. It would not send mail on its own. 
This service just receives mail from  senders and forwards/relays them to a recipient. Due the way how mail servers are configured, this process sometimes needs rewriting the email headers to forward the mail. 

What happened in your case is that the spam sender has protected its domain via something called a strict DMARC policy, which means emails from the sender can be sent only from its own server which would also mean that no other server/service will be able to forward that mail too without modifying the header.  Since forward-email is a email forwarding service, it needs to replace the FROM header with its own and have the actual sender's email address  as a reply-to. So, in future, if you receive any email from no-reply@forwardemail.net, just check the reply-to header and that is the actual sender.

Hope this clears.

**Comment by bauripalash** [comment]
@astrob0t I understood 👍 but you can see in the first screenshot there's no `reply-to` mail address visible 😕

**Comment by hungrycactus** [comment]
FWIW, I got a legit Amazon refund email but it was labeled as from "no-reply@forwardemail.net" and the reply-to is "return@amazon.com".  Are these emails (from:no-reply@forwardemail.net) from what I should expect when using forwardemail.net?

From: no-reply@forwardemail.net
To: mycustom@domain.com
Reply-To: return@amazon.com
Subject: Your refund confirmation
