### ISSUE TITLE
Outlook - Rejected #550 Permanent Failure

### ISSUE THREAD

**Issue by contactalexliu** [niftylettuce/forward-email#77]
Hi,

This seems to still be a problem with some Outlook users... Their mail is being rejected with `mx27.ess.sfj.cudaops.com #550 permanent failure for one of more recipients (<redacted> Please ensure the email service you are sending from either has SPF or DKIM. You can most...) ##`

- **SPF record:** `v=spf1 a mx include:spf.forwardemail.net include:<redacted> include:<redacted> -all`
- hosted on Cloudflare DNS

_Originally posted by @contactalexliu in https://github.com/niftylettuce/forward-email/issues/29#issuecomment-451018505_

**Comment by niftylettuce** [comment]
The issue is that the emails that are you sending FROM (e.g. Outlook) do not have SPF nor DKIM configured.   This is not a problem with ForwardEmail.net, this is a problem with configuration on the side of the person that is FROM.  It is a well-known standard that you should have at the very least DKIM or SPF setup on your domain name to ensure that emails are coming from who they say they are.

**Comment by contactalexliu** [comment]
I see. From what I can tell, the root domain in question does have SPF configured...
The diagnostic information is generated by what seems to be a local server `mprodmail.local1.wbcgp.com`, but the SPF record is for `wbcgp.com`. Could that be the issue?

**Comment by niftylettuce** [comment]
Please see <https://github.com/niftylettuce/forward-email/issues/101#issuecomment-471938509> for a detailed explanation.  You should be able to try again as of 6:00 AM EST today, 3/12/2019 and everything should send perfectly fine, and instant.
